#!/usr/bin/env python
# Copyright 2009 Paul Hummer
#
# This file is part of Tarmac.
#
# Tarmac is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by
# the Free Software Foundation.
#
# Tarmac is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Tarmac.  If not, see <http://www.gnu.org/licenses/>.

import sys

from tarmac.bin import TarmacLander

if __name__ == '__main__':
    script = TarmacLander()
    script.main()
    # Run the exit functions
    # On Windows, it seems that things like paramiko do not clean themselves up
    # properly if you let the stack unwind before running the atexit()
    # functions. So instead, we just force atexit() to be called here, and then
    # return
    sys.exitfunc()
