#!/usr/bin/env python
# vim:filetype=python
'''Main tarmac script.

This script will be the core of tarmac 0.3 and deploying as 'tarmac' - It will
handle the commands given to it, etc. spec=tarmac-0.3
'''

from tarmac.bin2.commands import main
main()
